import {createRequire} from 'node:module';import http from 'node:http';import path from 'node:path';import {readFile,mkdir,writeFile} from 'node:fs/promises';import {fileURLToPath} from 'node:url';import assert from 'node:assert/strict';
const require=createRequire(import.meta.url),{chromium}=require('playwright');const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),site=path.join(root,'dist/web'),evidence=path.join(root,'.qa/web-browser');await mkdir(evidence,{recursive:true});
const server=http.createServer(async(req,res)=>{try{const name=decodeURIComponent(new URL(req.url,'http://localhost').pathname).replace(/^\/Checkpoint\//,'')||'index.html',target=path.resolve(site,name);if(!target.startsWith(site+path.sep))throw new Error();const mime={'.html':'text/html','.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.webmanifest':'application/manifest+json'};res.writeHead(200,{'content-type':mime[path.extname(target)]||'application/octet-stream'});res.end(await readFile(target));}catch{res.writeHead(404);res.end();}});await new Promise(resolve=>server.listen(4173,'127.0.0.1',resolve));
const browser=await chromium.launch({headless:true,...(process.env.CHECKPOINT_BROWSER_CHANNEL?{channel:process.env.CHECKPOINT_BROWSER_CHANNEL}:{})}),context=await browser.newContext({viewport:{width:1280,height:900},serviceWorkers:'block'}),page=await context.newPage();const errors=[],checks=[],diagnostics=[];page.on('console',m=>{if(m.type()==='error')diagnostics.push(m.text());});page.on('requestfailed',r=>diagnostics.push(r.url()+': '+r.failure()?.errorText));page.on('pageerror',error=>errors.push(error.message));
const check=(pass,name)=>{assert.ok(pass,name);checks.push(name);console.log('PASS '+name);};
const click=async name=>page.getByRole('button',{name,exact:true}).first().click();
const input=async(name,value)=>page.getByRole('textbox',{name,exact:true}).fill(value);
const theme=async id=>page.waitForFunction(id=>document.documentElement.dataset.theme===id,id);
const own='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222',requestId='33333333-3333-4333-8333-333333333333';let libraryCalls=0,achievementCalls=0,authCalls=0,inviteBody,ownPublications=[],published=[],operations=new Map();
await context.route('https://fumdnvvvoiwoiziwtmsu.supabase.co/**',async route=>{const request=route.request(),url=new URL(request.url()),body=request.postDataJSON(),headers={'access-control-allow-origin':'*','access-control-allow-headers':'content-type, authorization, apikey','access-control-allow-methods':'GET,POST,PATCH,DELETE,OPTIONS'};const respond=(data,status=200)=>route.fulfill({status,headers,contentType:'application/json',body:data===null?'':JSON.stringify(data)});if(request.method()==='OPTIONS')return respond(null,204);
 if(url.pathname.endsWith('/auth/v1/token')){authCalls++;assert.equal(body.email,'browser_tester@accounts.checkpoint.invalid');return respond({access_token:'fixture-token',refresh_token:'fixture-refresh',expires_in:3600,user:{id:own}});}
 if(url.pathname.endsWith('/auth/v1/logout'))return respond(null,204);
 if(url.pathname.endsWith('/cp_profiles'))return respond([{user_id:own,display_name:'Fixture User',friend_code:'cp-123456abcdef'},{user_id:other,display_name:'Fixture Friend',friend_code:'cp-abcdef123456'}]);
 if(url.pathname.endsWith('/cp_friendships'))return respond([{user_low:own,user_high:other}]);
 if(url.pathname.endsWith('/cp_friend_requests')){if(request.method()==='POST'){inviteBody=body;return respond(null,201);}if(request.method()==='PATCH')return respond(null,204);return respond([{id:requestId,sender_id:other,recipient_id:own,status:'pending'}]);}
 if(url.pathname.endsWith('/cp_find_friend'))return respond([{user_id:other,display_name:'Fixture Friend',friend_code:'cp-abcdef123456'}]);
 if(url.pathname.endsWith('/cp_game_publications'))return respond(url.searchParams.get('owner_id')==='eq.'+own?ownPublications:[{owner_id:other,game_id:requestId,revision:1,is_shared:true,operation_payload:{title:'Friend game',platform:'PC',status:'playing',goalKind:'story',storyPercent:60,tasksDone:1,tasksTotal:3,achievementsUnlocked:7,achievementsTotal:12}}]);
 if(url.pathname.endsWith('/cp_publish_game')){const old=ownPublications.find(p=>p.game_id===body.p_game_id);if(operations.has(body.p_operation_id))return respond(operations.get(body.p_operation_id));if((old?.revision||0)!==body.p_expected_revision)return respond({code:'40001'},409);const revision=(old?.revision||0)+1,entry={owner_id:own,game_id:body.p_game_id,revision,is_shared:body.p_game!==null,operation_payload:body.p_game};ownPublications=ownPublications.filter(p=>p.game_id!==body.p_game_id);ownPublications.push(entry);published.push(body);operations.set(body.p_operation_id,revision);return respond(revision);}
 if(url.pathname.endsWith('/v1/auth/start'))return respond({flowId:'F'.repeat(43),pollSecret:'P'.repeat(43),authorizeUrl:'https://steamcommunity.com/openid/login?fixture=1'});
 if(url.pathname.endsWith('/v1/auth/poll'))return respond({status:'complete',token:'S'.repeat(43),steamId:'76561198000000000'});
 if(url.pathname.endsWith('/v1/library')){libraryCalls++;return respond({games:[{appId:620,name:'Portal 2',playtimeMinutes:90},{appId:999,name:'Borrowed family fixture',playtimeMinutes:25}]});}
 if(url.pathname.endsWith('/achievements')){achievementCalls++;return respond({achievements:[{id:'FIRST',name:'First',description:'Visible',hidden:false,unlocked:true},{id:'SECRET',name:'Hidden secret name',description:'Spoiler description',hidden:true,unlocked:false}]});}
 if(url.pathname.endsWith('/v1/auth/logout'))return respond({ok:true});return respond({error:'unknown fixture path'},404);
});
await context.route('https://steamcommunity.com/**',route=>route.fulfill({contentType:'text/html',body:'<title>Steam fixture</title>'}));await context.route('https://cdn.cloudflare.steamstatic.com/**',route=>route.abort());
try{
 await page.goto('http://127.0.0.1:4173/Checkpoint/');await page.locator('.window').waitFor();check(await page.getByRole('button',{name:'Añadir juego',exact:true}).count()>0,'browser application starts in Spanish without an account');
 await click('Iniciar sesión');await page.getByRole('textbox',{name:'Usuario de Checkpoint',exact:true}).waitFor();check(await page.getByRole('textbox',{name:'Nombre visible (para crear cuenta)',exact:true}).count()===0&&await page.getByRole('button',{name:'Entrar',exact:true}).isVisible(),'Spanish sign-in opens the existing-account form without registration fields');await page.screenshot({path:path.join(evidence,'web-login-es.png')});await click('Crear cuenta');await page.getByRole('textbox',{name:'Nombre visible (para crear cuenta)',exact:true}).waitFor();check(await page.getByRole('button',{name:'Ya tengo cuenta',exact:true}).isVisible()&&authCalls===0,'registration requires an explicit switch and does not submit login');await input('Contraseña de Checkpoint','fixture-switch-password');await click('Ya tengo cuenta');check(await page.getByRole('textbox',{name:'Nombre visible (para crear cuenta)',exact:true}).count()===0&&await page.getByRole('textbox',{name:'Contraseña de Checkpoint',exact:true}).inputValue()==='','returning to Spanish sign-in clears the password and registration fields');await click('Mi lista');
 await click('Añadir juego');await input('Nombre del juego','Browser fixture <img src=x>');await input('Notas privadas','Private fixture notes');await input('Tareas: una por línea. Usa [x] para las terminadas.','[x] Done task\n[ ] Next task');await click('Guardar');await page.locator('.game').first().waitFor();check((await page.locator('.game-title').textContent()).includes('<img')&&await page.locator('.game img').count()===0,'game creation saves notes/tasks and treats titles as text');
 await page.keyboard.press('F1');await page.locator('.shortcut-help[open]').waitFor();check((await page.locator('.shortcut-help').textContent()).includes('aplicación de Windows'),'web help explains unsupported global gestures');await page.keyboard.press('Escape');await page.reload();await page.locator('.game').first().waitFor();await page.locator('.game-tools button').nth(1).click();check(await page.getByRole('textbox',{name:'Notas privadas'}).inputValue()==='Private fixture notes','private library survives browser reload');await click('Cancelar');
 await click('Ajustes');await page.getByRole('combobox',{name:'Tema',exact:true}).selectOption('3');await theme('ocean');await page.keyboard.press('Escape');await theme('dark');check(await page.locator('.window').count()===1,'Escape cancels live theme preview and returns to the library');
 await click('Ajustes');await page.getByRole('combobox',{name:'Idioma'}).selectOption('1');await page.getByRole('combobox',{name:'Tema',exact:true}).selectOption('3');await click('Guardar');await page.getByRole('button',{name:'Settings',exact:true}).waitFor();check(await page.locator('html').getAttribute('lang')==='en','language switches the complete browser interface to English');
 await click('Settings');const colors=new Set();for(const [i,id]of ['dark','light','midnight','ocean','forest','plum','amber','contrast'].entries()){await page.getByRole('combobox',{name:'Theme',exact:true}).selectOption(String(i));await theme(id);colors.add(await page.locator('.dialog-page').evaluate(n=>getComputedStyle(n).backgroundColor));}check(colors.size===8,'all eight themes preview distinct colors');await click('Cancel');await theme('ocean');
 check(await page.locator('.window-mode').count()===0,'browser has no window size presets');
 for(const [width,height] of [[1440,900],[800,650],[390,844],[320,640],[1100,550],[1100,360]]){await page.setViewportSize({width,height});check(await page.locator('.window').evaluate(n=>{const r=n.getBoundingClientRect();return r.width>=innerWidth-26&&r.right<=innerWidth&&r.bottom<=innerHeight&&document.documentElement.scrollWidth<=innerWidth;}),'collection adapts to browser viewport '+width+'x'+height);if(width===1440||width===390)await page.screenshot({path:path.join(evidence,'web-responsive-'+width+'-en.png')});}
 await page.setViewportSize({width:1280,height:900});await click('Settings');check(await page.getByRole('combobox',{name:'Window mode',exact:true}).count()===0&&await page.getByRole('combobox',{name:'Miniature text size',exact:true}).count()===0,'web settings omit desktop sizing controls');await click('Cancel');
 await page.locator('.game-tools button').nth(1).click();check(await page.getByRole('textbox',{name:'Private notes'}).inputValue()==='Private fixture notes','responsive collection opens the saved game editor');await click('Cancel');
 for(let i=0;i<4;i++){await page.keyboard.press('F6');await page.waitForFunction(()=>window.checkpointState?.kind==='main');}check(await page.locator('.minirow').count()===0&&!await page.evaluate(()=>window.checkpointState.mini),'layout cycling never switches browser into a desktop window mode');
 const downloadPromise=page.waitForEvent('download');await click('Export backup');const download=await downloadPromise,stream=await download.createReadStream();let raw='';for await(const part of stream)raw+=part;const backup=JSON.parse(raw);check(backup.games[0].notes==='Private fixture notes'&&backup.games[0].tasks[0].done,'export includes private data and completed tasks for offline recovery');
 await writeFile(path.join(evidence,'import.json'),JSON.stringify({games:[backup.games[0],{title:'Imported Steam game',steamAppId:620,status:'Paused',notes:'Steam preserves me'}]}));await click('Import backup');await page.locator('input[type=file]').setInputFiles(path.join(evidence,'import.json'));await click('Import');await page.waitForFunction(()=>window.checkpointState?.kind==='main'&&window.checkpointState.games?.length===2);check(await page.locator('.game').count()===2,'JSON import deduplicates existing games and adds desktop-format games');
 await click('Settings');await click('Configure shortcuts');await page.screenshot({path:path.join(evidence,'web-shortcuts-en.png')});await page.getByRole('textbox',{name:'Add game',exact:true}).press('Control+Shift+N');await click('Save');await page.waitForFunction(()=>window.checkpointState?.kind==='main');await page.keyboard.press('Control+Shift+N');await page.getByRole('textbox',{name:'Game title'}).waitFor();check(true,'custom keyboard combination opens the game editor');await click('Cancel');await page.reload();await page.locator('.game').first().waitFor();await page.keyboard.press('Control+Shift+N');await page.getByRole('textbox',{name:'Game title'}).waitFor();check(true,'custom shortcuts persist after reload');await click('Cancel');await click('Settings');await click('Configure shortcuts');await page.getByRole('textbox',{name:'Search games',exact:true}).press('Control+Shift+N');await click('Save');await page.getByText('Some shortcuts are duplicated or reserved. Space and Escape are kept for navigation and closing.',{exact:true}).waitFor();check(true,'duplicate shortcuts are rejected without saving');await click('Restore defaults');await click('Save');await page.waitForFunction(()=>window.checkpointState?.kind==='main');await page.keyboard.press('Control+n');await page.getByRole('textbox',{name:'Game title'}).waitFor();check(true,'restore defaults restores the original working combinations');await click('Cancel');
 await click('Manage lists');await input('List name','Weekend');await click('Create list');await page.waitForFunction(()=>document.querySelector('select[aria-label="Game list"]').value==='1'&&!document.querySelector('input[aria-label="List name"]').disabled);await input('List name','Next');await click('Create list');await page.waitForFunction(()=>document.querySelector('select[aria-label="Game list"]').options.length===3&&!document.querySelector('input[aria-label="List name"]').disabled);await click('Save');await page.waitForFunction(()=>window.checkpointState?.kind==='main');await click('Add game');await input('Game title','Shared list fixture');await page.getByRole('checkbox',{name:'List: Weekend',exact:true}).check();await click('Save');await page.waitForFunction(()=>window.checkpointState?.kind==='main');check((await page.locator('.game-title').allTextContents()).includes('Shared list fixture'),'new game joins the active custom list');await page.getByRole('combobox',{name:'Game list',exact:true}).selectOption('custom:Weekend');await page.getByText('Shared list fixture',{exact:true}).waitFor();check(true,'one game belongs to two lists without duplicate copies');await page.reload();await page.getByText('Shared list fixture',{exact:true}).waitFor();check(await page.getByRole('combobox',{name:'Game list',exact:true}).inputValue()==='custom:Weekend','active list and memberships survive reload');
 await click('Manage lists');await page.getByRole('combobox',{name:'Game list',exact:true}).selectOption('1');await input('List name','Renamed weekend');await click('Rename list');await click('Save');await page.waitForFunction(()=>window.checkpointState?.kind==='main');check(await page.getByRole('combobox',{name:'Game list',exact:true}).inputValue()==='custom:Renamed weekend'&&await page.getByText('Shared list fixture',{exact:true}).count()===1,'renaming a list updates membership without cloning the game');await click('Manage lists');await page.getByRole('combobox',{name:'Game list',exact:true}).selectOption('2');await click('Remove list');await page.getByText('Next',{exact:true}).waitFor();await click('Remove list');await click('Save');await page.waitForFunction(()=>window.checkpointState?.kind==='main');check((await page.locator('.game-title').allTextContents()).includes('Shared list fixture'),'removing a list keeps its game and its other membership');
 await click('Add game');await input('Game title','Private from the start');await page.getByRole('checkbox',{name:'Private to my friends',exact:true}).check();await click('Save');await page.waitForFunction(()=>window.checkpointState?.kind==='main');check(await page.getByText('Private from the start',{exact:true}).count()===0,'a game created private is absent from public lists');await page.getByRole('combobox',{name:'Game list',exact:true}).selectOption('private');await page.getByText('Private from the start',{exact:true}).waitFor();check(true,'private games have their separate view');await page.screenshot({path:path.join(evidence,'web-private-games-en.png')});await click('Manage lists');await page.getByRole('checkbox',{name:'Create new games as private',exact:true}).check();await click('Save');await page.waitForFunction(()=>window.checkpointState?.kind==='main');await page.getByRole('combobox',{name:'Game list',exact:true}).selectOption('all');await click('Add game');check(await page.getByRole('checkbox',{name:'Private to my friends',exact:true}).isChecked(),'new games can default to private before their first save');await click('Cancel');await click('Manage lists');await page.getByRole('checkbox',{name:'Create new games as private',exact:true}).uncheck();await page.screenshot({path:path.join(evidence,'web-lists-en.png')});await click('Save');await page.waitForFunction(()=>window.checkpointState?.kind==='main');
 const legacyId='44444444-4444-4444-8444-444444444444';await page.evaluate(async({id,own})=>{const {BrowserStore}=await import('./store.mjs'),{normalize}=await import('./model.mjs'),store=await new BrowserStore().open(),library=await store.get('library');library.games.push(normalize({id,title:'Legacy private fixture',friendsPrivate:null}));await store.save(library,library.revision);await store.put('shares.'+own,{[id]:{selected:false,revision:0,published:null,desired:null,pending:null}});},{id:legacyId,own});await page.reload();await page.locator('.window').waitFor();
 await page.screenshot({path:path.join(evidence,'web-library-en.png')});await click('Sign in');await page.getByRole('textbox',{name:'Checkpoint username',exact:true}).waitFor();check(await page.getByRole('button',{name:'Create account',exact:true}).isVisible()&&await page.getByRole('textbox',{name:'Display name (for account creation)',exact:true}).count()===0,'English sign-in opens only the existing-account form');await page.screenshot({path:path.join(evidence,'web-login-en.png')});await click('Create account');await page.getByRole('textbox',{name:'Display name (for account creation)',exact:true}).waitFor();await click('I already have an account');check(await page.getByRole('textbox',{name:'Display name (for account creation)',exact:true}).count()===0&&authCalls===0,'English registration switches back to sign-in without an authentication request');await input('Checkpoint username','browser_tester');await input('Checkpoint password','fixture-not-a-real-password');const defaultPublication=page.waitForResponse(r=>r.url().includes('/cp_publish_game')&&r.request().method()==='POST'&&r.status()===200);await click('Sign in');await defaultPublication;await page.getByText('Fixture Friend',{exact:true}).waitFor();check(authCalls===1,'Checkpoint username/password authentication uses the configured service');
 await click('My account');await page.getByText('checkpoint-123456abcdef',{exact:true}).waitFor();check(!JSON.stringify(await page.evaluate(()=>window.checkpointState)).includes('fixture-token'),'account code uses full Checkpoint and snapshots exclude session tokens');
 await page.getByRole('button',{name:'Friends',exact:true}).last().click();await input('Friend code (checkpoint-…)','checkpoint-abcdef123456');await click('Send request');await page.waitForFunction(()=>document.body.textContent.includes('Request sent'));check(inviteBody.recipient_id===other,'friend invitation targets the Checkpoint identity');
 await click('View progress');await page.getByText('Friend game',{exact:true}).waitFor();check((await page.locator('.friends-content').textContent()).includes('60%'),'friends progress displays Checkpoint publications');await page.screenshot({path:path.join(evidence,'web-friends-en.png')});
 await click('Sharing');await page.getByText('Shared',{exact:true}).first().waitFor();check(published.some(p=>p.p_game)&&!published.some(p=>p.p_game?.title==='Private from the start'||p.p_game?.title==='Legacy private fixture')&&!JSON.stringify(published).includes('Private fixture notes'),'default sharing publishes listed games while excluding private games and notes');
 await page.getByRole('button',{name:'My list',exact:true}).click();await page.getByRole('combobox',{name:'Game list',exact:true}).selectOption('private');await page.getByText('Legacy private fixture',{exact:true}).waitFor();check(true,'migration preserves a legacy explicit private choice');await page.getByRole('combobox',{name:'Game list',exact:true}).selectOption('all');const withdrawal=page.waitForResponse(r=>r.url().includes('/cp_publish_game')&&r.request().postDataJSON()?.p_game===null&&r.status()===200);await page.locator('.game').filter({hasText:'Shared list fixture'}).click({button:'right'});await page.getByRole('menuitem',{name:'Move to private games',exact:true}).click();await withdrawal;await page.getByRole('combobox',{name:'Game list',exact:true}).selectOption('private');await page.getByText('Shared list fixture',{exact:true}).waitFor();check(published.some(p=>p.p_game===null),'moving a public game to private withdraws its server publication');await page.getByRole('combobox',{name:'Game list',exact:true}).selectOption('all');
 await page.getByRole('button',{name:'My list',exact:true}).click();await click('Settings');await click('Link Steam');await page.waitForFunction(()=>window.checkpointState?.kind==='main'&&!window.checkpointState.busy);await page.getByRole('button',{name:'Library',exact:true}).click();await page.getByText('Borrowed family fixture',{exact:true}).waitFor();check(libraryCalls>0&&achievementCalls>0,'Steam linking imports the library and synchronizes tracked achievements');const before=libraryCalls;await page.reload();await page.waitForFunction(()=>window.checkpointState?.kind==='main'&&!window.checkpointState.busy);check(libraryCalls>before,'Steam synchronization runs automatically on browser app reload');
 await page.getByRole('button',{name:'My list',exact:true}).click();await page.locator('.game').filter({hasText:'Imported Steam game'}).locator('.game-tools button').nth(1).click();check(await page.getByRole('textbox',{name:'Private notes'}).inputValue()==='Steam preserves me'&&await page.getByRole('combobox',{name:'Status',exact:true}).inputValue()==='2','Steam sync preserves manual state and notes');await click('Achievements');check(!(await page.locator('.dialog-page').textContent()).includes('Hidden secret name'),'locked hidden achievements remain spoilers until explicitly revealed');await click('Close');
 const storeCheck=await page.evaluate(async()=>{const {BrowserStore}=await import('./store.mjs'),s=await new BrowserStore().open(),value=await s.get('library');try{await s.save(value,value.revision-1);return false;}catch(e){return e.message==='local-conflict';}});check(storeCheck,'IndexedDB refuses stale writes instead of overwriting another tab');
 await click('Cancel');await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Settings',exact:true}).click();check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'settings fit a narrow mobile viewport');await page.screenshot({path:path.join(evidence,'web-mobile-en.png')});await click('Cancel');
 const offlineContext=await browser.newContext({serviceWorkers:'allow'}),offlinePage=await offlineContext.newPage();await offlinePage.goto('http://127.0.0.1:4173/Checkpoint/');await offlinePage.locator('.window').waitFor();await offlinePage.waitForFunction(()=>!!navigator.serviceWorker.controller);await offlineContext.setOffline(true);await offlinePage.reload();await offlinePage.locator('.window').waitFor();check(true,'the cached application opens offline after a first visit');await offlineContext.close();
 await page.setViewportSize({width:1280,height:900});await click('My account');await click('Sign out');await page.getByRole('textbox',{name:'Checkpoint username',exact:true}).waitFor();await page.getByRole('button',{name:'My list',exact:true}).click();check(await page.getByRole('button',{name:'Sign in',exact:true}).isVisible()&&!JSON.stringify(await page.evaluate(()=>window.checkpointState)).includes('fixture-token'),'signing out restores the visible login entry without exposing tokens');
 check(errors.length===0,'browser flow has no uncaught JavaScript errors');await writeFile(path.join(evidence,'report.json'),JSON.stringify({ok:true,checks:checks.length,names:checks},null,2));console.log('Browser checks passed: '+checks.length);
}catch(error){await page.screenshot({path:path.join(evidence,'failure.png')});console.error(error);await writeFile(path.join(evidence,'report.json'),JSON.stringify({ok:false,checks:checks.length,error:String(error),pageErrors:errors,authCalls,diagnostics},null,2));process.exitCode=1;}finally{await context.close();await browser.close();await new Promise(resolve=>server.close(resolve));}


