import {defaults,shortcutLabels,effectiveShortcuts,validateShortcuts} from './shortcuts.mjs';
import {normalize,mergeLibrary,importBackup,payload,friendCode,statuses,goals,themes,uuid,normalizeLists,listName,inList,shouldShare} from './model.mjs';
import {BrowserStore} from './store.mjs';
import {BrowserApi} from './api.mjs';

const [english,config]=await Promise.all(['en.json','config.json'].map(path=>fetch(path).then(r=>{if(!r.ok)throw new Error('configuration');return r.json();})));
const store=await new BrowserStore().open();
let data=await store.get('library')||{revision:0,games:[],deleted:[],settings:{language:'es',theme:'dark',layout:0,opacity:.88,syncMinutes:30,lightweight:false}};
data.games=(data.games||[]).map(normalize);data.deleted=(data.deleted||[]).slice(-20);data.settings={language:'es',theme:'dark',layout:0,opacity:.88,syncMinutes:30,lightweight:false,...data.settings};
data.settings.gameLists=normalizeLists([...(data.settings.gameLists||[]),...data.games.flatMap(g=>g.lists)]);data.settings.activeList=data.settings.activeList||'all';if(!['all','private'].includes(data.settings.activeList)&&!data.settings.gameLists.some(n=>'custom:'+n===data.settings.activeList))data.settings.activeList='all';
delete data.settings.mode;delete data.settings.miniSize;
if(!themes.includes(data.settings.theme))data.settings.theme='dark';
const api=new BrowserApi(config),listeners=[],controls=new Map();
let ack=0,tab='list',search='',filter=0,notice='',dialog,steamBusy=false,friendsBusy=false,authBusy=false,profiles=[],friendships=[],requests=[],publications=[],ownPublications=[],selectedFriend,friendPage='friends',friendFields={},authMode='login',shares={},shareUser,publishing=false,persistQueue=Promise.resolve(),storageConflict=false,loginGeneration=0;
const T=key=>data.settings.language==='en'?(english[key]||key):key;
const statusLabels=()=>['Pendiente','Jugando','Pausado','Historia terminada','Abandonado'].map(T);
const goalLabels=()=>['Historia','Todos los logros','Personalizado'].map(T);
const themeLabels=()=>['Oscuro','Claro','Medianoche','Océano','Bosque','Ciruela','Ámbar','Alto contraste','Púrpura cibernético','Azul eléctrico','Lima neón','Negro y rojo','Negro y naranja','Onda sintética','Azul y blanco','Púrpura oscuro','Esmeralda y neutro','Negro y blanco','Marino y cian','Coral y crema','Naranja y carbón','Índigo y gris suave'].map(T);
const game=id=>data.games.find(g=>g.id===id);
const send=value=>listeners.forEach(listener=>listener({data:value}));
const fail=error=>{
  const code=error?.code||error?.message;
  const keys={'igdb-not-configured':'El responsable de esta edición debe configurar IGDB en Supabase.','igdb-unavailable':'IGDB no está disponible. Inténtalo más tarde.','igdb-exhausted':'Has rechazado 200 carátulas para este juego. No se harán más búsquedas.','invalid-list':'El nombre de la lista debe tener entre 1 y 40 caracteres.','duplicate-list':'Ya existe una lista con ese nombre.','too-many-lists':'Puedes crear hasta 30 listas.','invalid-steam':'El ID de Steam debe ser un número positivo.','invalid-story':'La historia completada debe estar entre 0 y 100, o dejarse vacía.','duplicate-steam':'Ese juego de Steam ya está en la biblioteca.','invalid-shortcut':'Combinación no válida. Usa Ctrl, Alt o Shift y una tecla; las letras requieren Ctrl o Alt.','duplicate-shortcut':'Hay atajos repetidos o reservados. Espacio y Escape se conservan para navegar y cerrar.','invalid-user':'El usuario debe tener de 3 a 24 letras, números o guiones bajos, sin espacios.','invalid-code':'El código tiene el formato checkpoint- seguido de 12 caracteres.','invalid-game':'Escribe el nombre del juego.','invalid-backup':'La copia no es válida. No se han importado juegos.','local-conflict':'Otra pestaña ha cambiado la biblioteca. Exporta tus cambios y recarga antes de continuar.',storage:'No se pudo guardar. Exporta una copia antes de cerrar esta página.',
    invalid_credentials:'El usuario o la contraseña no son correctos.',user_already_exists:'Ese nombre de usuario ya está en uso.',email_exists:'Ese nombre de usuario ya está en uso.',weak_password:'Usa un nombre de 1 a 50 caracteres y una contraseña de al menos 8 caracteres.',unauthorized:'La sesión no es válida. Vuelve a entrar en Checkpoint.',forbidden:'No tienes permiso para consultar o cambiar estos datos.',rate:'Demasiadas consultas. Espera antes de volver a intentarlo.','40001':'El progreso cambió en otro equipo. Revisa el conflicto antes de publicar.','not-found':'No se encontró un usuario disponible con ese código.'};
  notice=T(keys[code]||'No se pudo completar la operación. Los datos locales se conservan.');if(dialog)dialog.error=notice;emit();
};
function persist(){data.settings.gameLists=normalizeLists([...(data.settings.gameLists||[]),...data.games.flatMap(g=>g.lists)]);planSharing();const snapshot=structuredClone({games:data.games,deleted:data.deleted,settings:data.settings});persistQueue=persistQueue.catch(()=>{}).then(async()=>{if(storageConflict)throw new Error('local-conflict');try{data.revision=await store.save(snapshot,data.revision);}catch(error){if(error.message==='local-conflict')storageConflict=true;throw error;}});persistQueue.catch(fail);scheduleSharing();return persistQueue;}
async function commit(){await persist();emit();}
function progress(g){if(g.goal===0&&g.storyPercent!=null)return {text:T('Historia · avance manual'),percent:g.storyPercent};if(g.goal===2&&g.tasks.length)return {text:`${g.tasks.filter(t=>t.done).length} / ${g.tasks.length} ${T('tareas')}`,percent:Math.round(g.tasks.filter(t=>t.done).length*100/g.tasks.length)};if(!g.achievements)return {text:T('Logros sin sincronizar'),percent:null};return {text:g.achievements.length?`${g.achievements.filter(a=>a.unlocked).length} / ${g.achievements.length} ${T('logros')}`:T('Sin logros de Steam'),percent:g.achievements.length?Math.round(g.achievements.filter(a=>a.unlocked).length*100/g.achievements.length):null};}
const cover=g=>g.customCover||(g.steamAppId?`https://cdn.cloudflare.steamstatic.com/steam/apps/${g.steamAppId}/library_600x900.jpg`:null);
function snapshot(){const p=data.settings;const sorted=data.games.filter(g=>(tab==='library'||inList(g,p.activeList))&&(filter===0||g.status===filter-1)&&g.title.toLocaleLowerCase().includes(search.toLocaleLowerCase())).sort((a,b)=>Number(b.favorite)-Number(a.favorite)||a.sortOrder-b.sortOrder||a.title.localeCompare(b.title));
 return {kind:'main',browser:true,signedIn:!!api.social,collection:p.activeList,collections:[{value:'all',label:T('Mi lista')},{value:'private',label:T('Privados')},...p.gameLists.map(name=>({value:'custom:'+name,label:name}))],shortcuts:effectiveShortcuts(p.shortcuts),language:p.language,theme:p.theme,light:['light','blue-white','emerald-neutral','coral-cream','indigo-gray'].includes(p.theme),opacity:p.opacity,mini:false,full:false,compact:p.layout===1,grid:p.layout===2,textSize:12,locked:true,pinned:false,globalHotkey:false,lightweight:p.lightweight,busy:steamBusy,tab,search,filter,ack,
  summary:`${data.games.filter(g=>g.tracked).length} ${T('en tu lista')} · ${data.games.filter(g=>g.status===3).length} ${T('historias terminadas')}`,
  connection:api.steam?T('● Steam vinculado'):api.social?T('● Checkpoint conectado'):T('● Biblioteca en este navegador'),notice,
  emptyTitle:T('Un juego cada vez'),emptyText:T('Añade un juego o importa tu biblioteca de Steam. Elige después cuáles quieres tener a mano.'),examples:data.games.length===0,undo:data.deleted.length>0,
  labels:{account:T(api.social?'Mi cuenta':'Iniciar sesión'),tagline:T('UN JUEGO CADA VEZ'),title:T('Tu próxima aventura'),friendsTitle:T('Tu gente, tus aventuras'),list:T('Mi lista'),library:T('Biblioteca'),friends:T('Amigos'),add:T('Añadir juego'),settings:T('Ajustes'),hide:T('Cerrar menús o ayuda'),close:T('Cerrar'),pin:T('Mantener siempre visible'),search:T('Buscar juego'),sync:T('Actualizar'),details:T('Ver ficha completa'),achievements:T('Ver logros'),steam:T('Conectar Steam'),edit:T('Editar juego'),exitMini:T('Salir de miniatura'),locked:T('Bloquear posición y tamaño'),view:T('Cambiar vista'),undo:T('Recuperar último juego eliminado'),examples:T('Añadir ejemplos'),finish:T('Marcar o desmarcar historia terminada'),windowMode:T('Modo de ventana'),fullWindow:T('Ventana completa'),smallWindow:T('Ventana pequeña'),miniature:T('Miniatura'),collection:T('Lista de juegos'),manageLists:T('Gestionar listas'),makePrivate:T('Mover a Privados'),makeVisible:T('Hacer visible para amigos'),configureShortcuts:T('Configurar atajos'),shortcuts:T('Atajos de teclado'),generalKeys:T('En la ventana principal'),miniKeys:T('En miniatura'),orderKeys:T('Al enfocar el botón de reordenar'),helpHint:T('Pulsa F1 para ver todos los atajos.'),closeHelp:T('Cerrar ayuda'),selectGame:T('Seleccionar juego'),firstLast:T('Primer o último juego'),pageGame:T('Avanzar o retroceder una página'),gameMenu:T('Abrir menú del juego'),reorder:T('Reordenar juego'),undoContext:T('Fuera de los campos de texto'),hideContext:'',globalKeys:T('Mostrar / ocultar desde cualquier aplicación'),globalUnavailable:T('Este atajo solo está disponible en la aplicación de Windows.'),homeEnd:T('Inicio / Fin'),pageKeys:T('RePág / AvPág'),enterSpace:T('Intro / Espacio'),all:T('Todos'),statuses:statusLabels(),backupImport:T('Importar copia'),backupExport:T('Exportar copia'),browserInfo:T('Sobre la versión web'),windowsDownload:T('Descargar para Windows')},
  games:sorted.map(g=>({id:g.id,title:g.title,platform:g.platform+(g.playtimeMinutes?` · ${(g.playtimeMinutes/60).toFixed(1)} h`:''),state:g.status,status:statusLabels()[g.status],next:g.tasks.find(t=>!t.done)?.title||goalLabels()[g.goal],achievementCaption:g.achievements?.length?`${T("Logros")} · ${g.achievements.filter(a=>a.unlocked).length} / ${g.achievements.length}`:T("Ver logros"),progress:progress(g).text,percent:progress(g).percent,favorite:g.favorite,friendsPrivate:g.friendsPrivate===true,cover:p.lightweight?null:cover(g)})),friendsBusy,friends:tab==='friends'?friendsSchema():null};}
function emit(){const p=data.settings;send(dialog?{kind:'dialog',language:p.language,theme:p.theme,light:['light','blue-white','emerald-neutral','coral-cream','indigo-gray'].includes(p.theme),ack,root:dialog.render()}:snapshot());}
const text=(value,heading=false,muted=false)=>({type:'text',text:value,heading,muted,children:[]});
function build(prefix,fields){const b={fields,n:0};
 b.button=(label,run,tag)=>{const id=prefix+'.'+(tag||++b.n);controls.set(id,run);return {id,type:'button',text:label,enabled:!b.busy,children:[]};};
 b.field=(key,label,type='input',options)=>{const id=prefix+'.field.'+key;controls.set(id,async value=>{fields[key]=value;if(b.onChange)await b.onChange(key,value);});const node={id,type,name:label,text:label,max:type==='textarea'?20000:250,enabled:!b.busy,value:type==='password'?undefined:fields[key],checked:fields[key]===true,empty:!fields[key],options,children:[]};return type==='check'?[node]:[text(label,false,true),node];};
 b.page=(heading,description,items,actions)=>({pageId:prefix,type:'dock',children:[{type:'scroll',children:[{type:'stack',children:[text(heading,true),text(description,false,true),...(dialog?.error?[text(dialog.error,false,true)]:[]),...items]}]},{type:'row',children:actions}]});return b;}
const coverQueue=new Set(),coverAttempts=new Set();let coverBusy=false;
function missingCover(id){const g=game(id);if(g?.tracked&&!g.customCover&&g.igdbCoverSearchTitle!==g.title&&coverAttempts.size<10&&coverQueue.size<10&&!coverAttempts.has(g.id+'|'+g.title))coverQueue.add(id);}
setInterval(async()=>{if(coverBusy||dialog||document.hidden||document.querySelector('.menu,.shortcut-help:modal')||tab==='friends'||data.settings.lightweight)return;if(coverAttempts.size>=10){coverQueue.clear();return;}const id=coverQueue.values().next().value;if(!id)return;coverQueue.delete(id);const g=game(id);if(!g||!g.tracked||g.customCover||g.igdbCoverSearchTitle===g.title)return;coverAttempts.add(g.id+'|'+g.title);await findCover(g,g.title,null,true);},3000);
async function findCover(g,title,parent,automatic=false,builder){
 if(coverBusy)return;coverBusy=true;if(builder)builder.busy=true;emit();
 const remember=async()=>{const current=game(g.id);if(automatic){await persist();}else if(current){current.rejectedIgdbCovers=[...g.rejectedIgdbCovers];current.igdbCoverSearchTitle=g.igdbCoverSearchTitle;await persist();}};
 try{
  if(!title||title.length>140)throw new Error('invalid-game');if(g.rejectedIgdbCovers.length>=200)throw new Error('igdb-exhausted');
  const result=await api.coverSearch(title,g.rejectedIgdbCovers,!automatic);if((dialog||null)!==parent)return;
  const candidate=result?.candidate;if(candidate==null){g.igdbCoverSearchTitle=title;await remember();if(!automatic)notice=T('No hay otra carátula de IGDB disponible para este nombre.');return;}
  if(!Number.isSafeInteger(candidate.id)||candidate.id<1||typeof candidate.name!=='string'||candidate.name.length>250||!candidate.name||!(/^[A-Za-z0-9_-]{1,80}$/).test(candidate.imageId)||g.rejectedIgdbCovers.includes(candidate.imageId))throw new Error('igdb-unavailable');
  const blob=await api.coverImage(candidate.imageId),bitmap=await createImageBitmap(blob);let png;
  try{if(bitmap.width*bitmap.height>16000000)throw new Error('igdb-unavailable');const scale=Math.min(1,160/bitmap.width,240/bitmap.height),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);png=canvas.toDataURL('image/png');}finally{bitmap.close();}
  if((dialog||null)!==parent||automatic&&(!game(g.id)||g.customCover||g.title!==title||data.settings.lightweight))return;
  g.igdbCoverSearchTitle=title;
  const choice=build('cover-choice',{});let deciding=false;
  const decide=async accept=>{if(deciding)return;deciding=true;choice.busy=true;emit();try{if(accept){g.customCover=png;g.igdbCoverImageId=candidate.imageId;}else if(!g.rejectedIgdbCovers.includes(candidate.imageId))g.rejectedIgdbCovers.push(candidate.imageId);await remember();dialog=parent||undefined;emit();}catch(error){choice.busy=false;deciding=false;fail(error);}};
  dialog={cancel:()=>decide(false),render:()=>choice.page(T('Carátula de IGDB'),title,[{type:'image',src:png,style:'cover-preview',children:[]},text(candidate.name+(Number.isInteger(candidate.year)?' · '+candidate.year:''),true),text(T('Coincidencia más cercana por nombre. Comprueba que sea tu juego. Carátula: IGDB.')),text(T('Si la rechazas no volveremos a ofrecerla. Puedes buscar otra desde el editor del juego.'))],[choice.button(T('No usar esta carátula'),()=>decide(false),'reject'),choice.button(T('Usar esta carátula'),()=>decide(true),'accept')])};
 }catch(error){if(!automatic&&dialog===parent)fail(error);}
 finally{coverBusy=false;if(builder)builder.busy=false;emit();}
}
function closeDialog(){dialog=null;emit();}
function info(){const b=build('info',{});dialog={render:()=>b.page(T('Checkpoint en tu navegador'),T('La biblioteca privada se guarda en este navegador. Exporta copias: borrar los datos del sitio elimina la biblioteca local.'),[text(T('Steam y amigos requieren conexión. La sesión se conserva en esta pestaña; al cerrarla puede ser necesario volver a entrar.')),text(T('La interfaz se adapta al tamaño de tu navegador. Usa Mi lista o Biblioteca; la bandeja y los atajos globales están en la app de Windows.')),text(T('Los archivos JSON de la app de Windows se pueden importar. La biblioteca privada no se sincroniza automáticamente entre dispositivos.'))],[b.button(T('Cerrar'),closeDialog,'close')])};emit();}
function editor(original){const draft=original?structuredClone(original):normalize({title:T('Nuevo juego'),sortOrder:data.games.length,friendsPrivate:data.settings.newGamesPrivate===true||data.settings.activeList==='private',lists:data.settings.activeList.startsWith('custom:')?[data.settings.activeList.slice(7)]:[]});const fields={title:original?.title||'',platform:draft.platform,steamAppId:draft.steamAppId||'',status:draft.status,goal:draft.goal,customGoal:draft.customGoal,storyPercent:draft.storyPercent??'',notes:draft.notes,friendsPrivate:draft.friendsPrivate===true,tracked:draft.tracked,favorite:draft.favorite,tasks:draft.tasks.map(t=>`[${t.done?'x':' '}] ${t.title}`).join('\n')};for(const name of data.settings.gameLists)fields['list.'+name]=draft.lists.some(n=>n.toLocaleLowerCase()===name.toLocaleLowerCase());const b=build('editor',fields);
 b.onChange=async(key,value)=>{if(key==='cover'&&value){if(value.size>2097152||!['image/png','image/jpeg','image/webp'].includes(value.type))throw new Error('cover');const bitmap=await createImageBitmap(value);try{if(bitmap.width*bitmap.height>16000000)throw new Error('cover');const scale=Math.min(1,160/bitmap.width,240/bitmap.height),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);draft.customCover=canvas.toDataURL('image/png');draft.igdbCoverImageId='';}finally{bitmap.close();}}};
 dialog={gameId:original?.id,render:()=>{const items=[...b.field('title',T('Nombre del juego')),...b.field('platform',T('Plataforma')),...b.field('steamAppId',T('ID de aplicación de Steam (opcional)')),...b.field('status',T('Estado'),'select',statusLabels()),...b.field('goal',T('Objetivo'),'select',goalLabels()),...b.field('customGoal',T('Objetivo personal')),...b.field('storyPercent',T('Avance de historia (0–100, opcional)')),...b.field('tracked',T('Mostrar en Mi lista'),'check'),...b.field('friendsPrivate',T('Privado para mis amigos'),'check'),text(T('Los juegos de tus listas son visibles para tus amigos salvo que los marques privados. Notas y nombres de tareas siguen siendo privados.')),text(T('Sin conexión, los cambios de visibilidad se aplican a tus amigos cuando vuelva la conexión.')),...data.settings.gameLists.flatMap(name=>b.field('list.'+name,T('Lista: ')+name,'check')),...b.field('favorite',T('Favorito'),'check'),...b.field('tasks',T('Tareas: una por línea. Usa [x] para las terminadas.'),'textarea'),...b.field('notes',T('Notas privadas'),'textarea'),...b.field('cover',T('Carátula local (PNG, JPEG o WebP, hasta 2 MiB)'),'file')];items.at(-1).accept='image/png,image/jpeg,image/webp';if(draft.customCover)items.push({type:'image',src:draft.customCover,children:[]});
 items.push(b.button(T('Buscar otra carátula en IGDB'),()=>findCover(draft,String(fields.title).trim(),dialog,false,b),'igdb'));
 const actions=[b.button(T('Cancelar'),closeDialog,'cancel'),b.button(T('Guardar'),async()=>{if(fields.steamAppId && (!/^\d+$/.test(String(fields.steamAppId).trim())||Number(fields.steamAppId)<1||Number(fields.steamAppId)>2147483647))throw new Error('invalid-steam');if(fields.storyPercent!==''&&(!/^\d+$/.test(String(fields.storyPercent))||Number(fields.storyPercent)>100))throw new Error('invalid-story');const candidate=normalize({...draft,...fields,lists:data.settings.gameLists.filter(name=>fields['list.'+name]),steamAppId:fields.steamAppId||null,storyPercent:fields.storyPercent===''?null:Number(fields.storyPercent),status:Number(fields.status),goal:Number(fields.goal),tasks:String(fields.tasks).split('\n').map(line=>{const match=line.match(/^\s*\[([xX ])\]\s*(.*)$/);return {title:match?match[2]:line.trim(),done:!!match&&match[1].toLowerCase()==='x'};})});if(!candidate.title)throw new Error('invalid-game');if(candidate.steamAppId&&data.games.some(g=>g.id!==candidate.id&&g.steamAppId===candidate.steamAppId))throw new Error('duplicate-steam');if(original){const current=game(original.id);if(!current)throw new Error('invalid-game');candidate.achievements=current.achievements;candidate.playtimeMinutes=current.playtimeMinutes;candidate.syncedAt=current.syncedAt;data.games[data.games.indexOf(current)]=candidate;}else data.games.push(candidate);await persist();closeDialog();},'save')];if(original){actions.unshift(b.button(T('Logros'),()=>achievements(original.id,dialog),'achievements'),b.button(T('Eliminar'),()=>confirmDelete(original.id),'delete'));}return b.page(original?T('Editar juego'):T('Añadir juego'),T('La historia se marca manualmente. Los logros de Steam no la completan.'),items,actions);}};emit();}
function gameDetails(id){if(!game(id))return;const b=build('game-details',{});
 dialog={render:()=>{const g=game(id);if(!g)return b.page(T('Ficha del juego'),T('Juego no disponible'),[],[b.button(T('Cerrar'),closeDialog,'close')]);const p=progress(g),all=g.achievements||[];
 const items=[];if(!data.settings.lightweight&&cover(g))items.push({type:'image',src:cover(g),style:'cover-preview',children:[]});
 items.push(text(g.platform+' · '+statusLabels()[g.status],true),text(T('Objetivo')+': '+(g.goal===2?(g.customGoal||T('Objetivo personal')):goalLabels()[g.goal])),text(p.text+(p.percent==null?'':' · '+p.percent+'%')));
 if(p.percent!=null)items.push({type:'progress',value:p.percent,max:100,name:T('Progreso'),children:[]});
 items.push({type:'card',style:'achievement-summary',children:[text(T('Logros'),true),text('Steam: '+(g.achievements===null?T('Sin sincronizar'):all.filter(a=>a.unlocked).length+' / '+all.length)),text('RetroAchievements: '+(g.retroAchievements===null?T('Sin sincronizar'):g.retroAchievements.filter(a=>a.unlocked).length+' / '+g.retroAchievements.length)),text(T('Objetivos manuales')+': '+g.manualAchievements.length)]});
 items.push(text(T('Tiempo jugado')+': '+(g.playtimeMinutes/60).toLocaleString(data.settings.language,{maximumFractionDigits:1})+' h'),text(T('Visibilidad')+': '+T(g.friendsPrivate?'Privado para mis amigos':'Visible para mis amigos')),text(T('Listas')+': '+(g.lists.join(', ')||T('Sin listas adicionales'))),text(T('Tareas'),true));
 items.push(...(g.tasks.length?g.tasks.map(t=>text((t.done?'✓ ':'○ ')+t.title)):[text(T('Sin tareas'))]));items.push(text(T('Notas'),true),text(g.notes||T('Sin notas')));
 const date=value=>value?new Date(value).toLocaleString(data.settings.language):T('Sin sincronizar');items.push(text(T('Añadido')+': '+date(g.addedAt)),text(T('Última sincronización')+': '+date(g.syncedAt)));if(g.finishedAt)items.push(text(T('Historia terminada')+': '+date(g.finishedAt)));if(g.steamAppId)items.push(text('Steam ID: '+g.steamAppId));if(g.retroGameId)items.push(text('RetroAchievements ID: '+g.retroGameId));
 return b.page(g.title,T('Ficha del juego'),items,[b.button(T('Cerrar'),closeDialog,'close'),b.button(T('Editar juego'),()=>editor(g),'edit'),b.button(T('Ver logros'),()=>achievements(id,dialog),'achievements')]);}};emit();}
function confirmDelete(id){const g=game(id);if(!g)return;const b=build('delete',{});dialog={render:()=>b.page(T('Eliminar juego'),g.title,[text(T('Podrás recuperar este juego desde Deshacer. Su publicación se retirará cuando haya conexión.'))],[b.button(T('Cancelar'),()=>editor(g),'cancel'),b.button(T('Eliminar'),async()=>{data.deleted.push(structuredClone(g));data.deleted=data.deleted.slice(-20);data.games=data.games.filter(x=>x.id!==id);if(shares[id]?.selected){shares[id].selected=false;shares[id].desired=null;await saveShares();}await persist();closeDialog();},'delete')])};emit();}
function achievements(id,parent){if(!game(id))return;const fields={spoilers:false,pending:true},expanded=new Set(),b=build('achievements',fields);
 dialog={render:()=>{const g=game(id),all=g?.achievements||[],done=all.filter(a=>a.unlocked).length;
 const items=[{type:'card',style:'achievement-summary',children:[text(`${done} / ${all.length} ${T('logros completados')}`,true),{type:'progress',value:all.length?done*100/all.length:0,max:100,name:T('Logros'),children:[]},text(all.length?`${all.length-done}${T(' logros pendientes')}`:T('Logros sin sincronizar'))]},...b.field('spoilers',T('Mostrar logros ocultos'),'check'),...b.field('pending',T('Solo pendientes'),'check')];
 for(const a of all.filter(a=>!fields.pending||!a.unlocked).sort((a,b)=>Number(a.unlocked)-Number(b.unlocked))){const hidden=a.hidden&&!a.unlocked&&!fields.spoilers;
 const children=[text((a.unlocked?'✓ ':'○ ')+(hidden?T('Logro oculto'):a.name),true),text('Steam',false,true)];
 if(hidden)children.push(text(T('Activa la opción superior para revelar este logro.')));
 else {const toggle=b.button(T(expanded.has(a.id)?'Ocultar descripción':'Ver descripción'),()=>{if(!expanded.delete(a.id))expanded.add(a.id);},'description.'+a.id);toggle.name=toggle.text+' · '+a.name;children.push(toggle);if(expanded.has(a.id))children.push({...text(a.description||T('Este logro no tiene descripción.')),style:'achievement-description'});}
 items.push({type:'card',style:'achievement-card',children});}
 return b.page(T('Logros'),g?.title||'',items,[b.button(T('Cerrar'),()=>{if(parent){dialog=parent;emit();}else closeDialog();},'close'),{...b.button(T('Actualizar'),async()=>{await sync(id);emit();},'sync'),enabled:!!api.steam&&!steamBusy&&!!g?.steamAppId}]);}};emit();}
function settings(){const previous=structuredClone(data.settings),fields={language:data.settings.language==='en'?1:0,theme:themes.indexOf(data.settings.theme),layout:data.settings.layout,opacity:data.settings.opacity,interval:[15,30,60,120].indexOf(data.settings.syncMinutes),lightweight:data.settings.lightweight};const b=build('settings',fields);b.onChange=(key,value)=>{if(key==='theme')data.settings.theme=themes[Number(value)]||'dark';if(key==='opacity')data.settings.opacity=Number(value);};
 dialog={cancel:async()=>{data.settings=previous;await persist();closeDialog();},render:()=>{const items=[...b.field('language',T('Idioma'),'select',[T('Español'),T('Inglés')]),...b.field('theme',T('Tema'),'select',themeLabels()),text(T('Vista previa inmediata. Guarda para conservar el tema; Cancelar recupera el anterior.'),false,true),...b.field('layout',T('Vista de la colección'),'select',[T('Lista'),T('Compacta'),T('Cuadrícula de carátulas')]),...b.field('opacity',T('Opacidad del fondo'),'slider'),...b.field('lightweight',T('Modo ligero (sin carátulas)'),'check'),...b.field('interval',T('Sincronizar biblioteca y logros al abrir y cada…'),'select',[15,30,60,120].map(n=>`${n} ${T('minutos')}`)),text(api.steam?T('Steam vinculado.'):T('Cuenta sin vincular. El inicio de sesión se realiza en Steam.')),b.button(api.steam?T('Desvincular Steam'):T('Vincular Steam'),async()=>{data.settings=previous;await persist();if(api.steam)await api.unlink();else connectSteam();closeDialog();},'steam'),b.button(T('Gestionar listas'),async()=>{data.settings=previous;await persist();closeDialog();manageLists();},'lists'),b.button(T('Configurar atajos'),async()=>{data.settings=previous;await persist();shortcutSettings();},'shortcuts'),b.button(T('Sobre la versión web'),async()=>{data.settings=previous;await persist();info();},'info')];const slider=items.find(x=>x.type==='slider');Object.assign(slider,{min:.35,max:1,step:.05});return b.page(T('Ajustes'),T('Ajusta Checkpoint para que encaje contigo.'),items,[b.button(T('Cancelar'),async()=>{data.settings=previous;await persist();closeDialog();},'cancel'),b.button(T('Guardar'),async()=>{data.settings={...data.settings,language:Number(fields.language)===1?'en':'es',theme:themes[fields.theme]||'dark',layout:Number(fields.layout),opacity:Number(fields.opacity),syncMinutes:[15,30,60,120][fields.interval]||30,lightweight:fields.lightweight===true};await persist();restartTimer();closeDialog();},'save')]);}};emit();}
function manageLists(){const fields={selected:0,name:'',newGamesPrivate:data.settings.newGamesPrivate===true},b=build('lists',fields);b.onChange=(key,value)=>{if(key==='selected')fields.name=data.settings.gameLists[Number(value)-1]||'';};const change=async(rename)=>{if(b.busy)return;const old=rename?data.settings.gameLists[Number(fields.selected)-1]:null;if(rename&&!old)return;const next=listName(fields.name,data.settings.gameLists,old);b.busy=true;emit();try{if(old){data.settings.gameLists=data.settings.gameLists.map(n=>n.toLocaleLowerCase()===old.toLocaleLowerCase()?next:n);for(const g of [...data.games,...data.deleted])g.lists=normalizeLists(g.lists.map(n=>n.toLocaleLowerCase()===old.toLocaleLowerCase()?next:n));}else data.settings.gameLists.push(next);data.settings.activeList='custom:'+next;await persist();fields.selected=data.settings.gameLists.indexOf(next)+1;fields.name=next;}finally{b.busy=false;emit();}};dialog={render:()=>b.page(T('Gestionar listas'),T('Un juego puede estar en varias listas sin duplicarse. Los privados se consultan en Privados.'),[...b.field('selected',T('Lista de juegos'),'select',[T('Nueva lista'),...data.settings.gameLists]),...b.field('name',T('Nombre de la lista')),...b.field('newGamesPrivate',T('Crear juegos nuevos como privados'),'check'),text(T('Quitar una lista conserva sus juegos, su privacidad y el resto de listas.')),b.button(T('Crear lista'),()=>change(false),'create'),b.button(T('Renombrar lista'),()=>change(true),'rename'),b.button(T('Quitar lista'),()=>{const name=data.settings.gameLists[Number(fields.selected)-1];if(!name)return;const parent=dialog,c=build('remove-list',{});dialog={render:()=>c.page(T('Quitar lista'),name,[text(T('Quitar una lista conserva sus juegos, su privacidad y el resto de listas.'))],[c.button(T('Cancelar'),()=>{dialog=parent;emit();},'cancel'),c.button(T('Quitar lista'),async()=>{data.settings.gameLists=data.settings.gameLists.filter(n=>n!==name);for(const g of [...data.games,...data.deleted])g.lists=g.lists.filter(n=>n.toLocaleLowerCase()!==name.toLocaleLowerCase());data.settings.activeList='all';await persist();fields.selected=0;fields.name='';dialog=parent;emit();},'remove')])};emit();},'remove')],[b.button(T('Cancelar'),closeDialog,'cancel'),b.button(T('Guardar'),async()=>{data.settings.newGamesPrivate=fields.newGamesPrivate===true;await persist();closeDialog();},'save')])};emit();}
function shortcutSettings(){const fields=effectiveShortcuts(data.settings.shortcuts),b=build('shortcuts',fields);dialog={render:()=>{const items=[text(T('Pulsa una combinación en cada campo. Tab cambia de campo; Escape cancela. No se permiten atajos repetidos.')),text(T('Los atajos del navegador pueden tener prioridad. El atajo global solo funciona en Windows.'))];for(const key of Object.keys(defaults).filter(k=>k!=='global')){const nodes=b.field(key,T(shortcutLabels[key]));nodes.find(n=>n.type==='input').shortcut=true;items.push(...nodes);}return b.page(T('Configurar atajos'),T('Los cambios se aplican al guardar.'),items,[b.button(T('Restablecer predeterminados'),()=>{Object.assign(fields,defaults);emit();},'reset'),b.button(T('Cancelar'),closeDialog,'cancel'),b.button(T('Guardar'),async()=>{data.settings.shortcuts=validateShortcuts(fields);await persist();closeDialog();},'save')]);}};emit();}
async function sync(single){if(steamBusy||!api.steam)return;steamBusy=true;emit();try{if(!single){const library=await api.steamRequest('v1/library');mergeLibrary(data.games,library.games||[]);if(!data.games.some(g=>g.tracked))tab='library';await persist();}
 const selected=single?[game(single)].filter(Boolean):data.games.filter(g=>g.tracked&&g.steamAppId).sort((a,b)=>(a.syncedAt||'').localeCompare(b.syncedAt||'')).slice(0,20);let errors=0;
 for(const current of selected){try{const result=await api.steamRequest(`v1/games/${current.steamAppId}/achievements?lang=${data.settings.language}`);const target=game(current.id);if(target){target.achievements=normalize({...target,achievements:result.achievements}).achievements;target.syncedAt=new Date().toISOString();await persist();}}catch{errors++;}}
 notice=T(errors?'Algunos logros no se pudieron actualizar. Se conserva el progreso anterior.':'Biblioteca y progreso de Steam actualizados.');}catch(error){fail(error);}finally{steamBusy=false;emit();}}
async function connectSteam(){const popup=window.open('about:blank','checkpoint-steam-login');const generation=++loginGeneration;steamBusy=true;emit();try{const flow=await api.steamRequest('v1/auth/start',{},false),url=new URL(flow.authorizeUrl);if(url.origin!=='https://steamcommunity.com'||url.pathname!=='/openid/login')throw new Error('remote');if(popup)popup.location.href=url.href;
 const b=build('steam',{});dialog={render:()=>b.page(T('Vincular Steam'),T('Termina el acceso en Steam y vuelve a esta página.'),[b.button(T('Abrir Steam'),()=>window.open(url.href,'_blank','noopener,noreferrer'),'open')],[b.button(T('Cancelar'),()=>{loginGeneration++;steamBusy=false;closeDialog();},'cancel')])};emit();
 const expires=Date.now()+600000;while(generation===loginGeneration&&Date.now()<expires){await new Promise(r=>setTimeout(r,2000));const result=await api.steamRequest('v1/auth/poll',{flowId:flow.flowId,pollSecret:flow.pollSecret},false);if(generation!==loginGeneration)return;if(result.status==='complete'){if(!/^[A-Za-z\d_-]{43}$/.test(result.token)||!/^7656119\d{10}$/.test(result.steamId))throw new Error('auth');api.steam={token:result.token,steamId:result.steamId};api.save('checkpoint-steam',api.steam);closeDialog();popup?.close();break;}}if(!api.steam&&generation===loginGeneration)throw new Error('remote');}catch(error){popup?.close();fail(error);}finally{if(generation===loginGeneration){steamBusy=false;emit();if(api.steam)await sync();}}}
async function loadFriends(){if(friendsBusy||!api.social)return;friendsBusy=true;emit();try{const user=api.social.user.id;const results=await Promise.all([api.profiles(),api.friendships(),api.requests(),api.publications(user)]);if(api.social?.user.id!==user)return;[profiles,friendships,requests,ownPublications]=results;if(selectedFriend)publications=(await api.publications(selectedFriend)).filter(p=>p.is_shared&&p.operation_payload);await attachShares();}catch(error){profiles=[];friendships=[];requests=[];publications=[];ownPublications=[];fail(error);}finally{friendsBusy=false;emit();}}
async function attachShares(){const user=api.social?.user.id;if(user===shareUser)return;shareUser=user;shares=user?(await store.get('shares.'+user)||{}):{};if(user){let changed=false;for(const g of data.games)if(g.friendsPrivate===null){g.friendsPrivate=shares[g.id]?.selected===false;changed=true;}if(changed)await persist();}}
const saveShares=()=>shareUser?store.put('shares.'+shareUser,shares):Promise.resolve();
const samePayload=(a,b)=>JSON.stringify(a,Object.keys(a||{}).sort())===JSON.stringify(b,Object.keys(b||{}).sort());
function planSharing(){if(!shareUser||api.social?.user.id!==shareUser)return;for(const g of data.games){const desired=shouldShare(g)?payload(g):null;let entry=shares[g.id];if(!entry&&desired){const remote=ownPublications.find(p=>p.game_id===g.id);entry=shares[g.id]={revision:remote?.revision||0,published:remote?.operation_payload||null,pending:null,conflict:false};}if(entry){entry.selected=desired!==null;entry.desired=desired;}}for(const [id,entry] of Object.entries(shares))if(!game(id)){entry.selected=false;entry.desired=null;}}
let publicationTimer;
function scheduleSharing(){clearTimeout(publicationTimer);publicationTimer=setTimeout(()=>flush().catch(fail),2000);}
async function flush(){if(publishing||!api.social||!navigator.onLine)return;await attachShares();if(publishing)return;publishing=true;planSharing();const owner=shareUser;try{await saveShares();for(const [id,entry] of Object.entries(shares)){if(entry.conflict&&entry.desired!==null)continue;for(let pass=0;pass<3;pass++){if(owner!==api.social?.user.id)throw new Error('auth');
 if(entry.desired===null&&entry.pending?.payload){const remote=(await api.publications(owner)).find(p=>p.game_id===id);entry.revision=remote?.revision||0;entry.published=remote?.operation_payload||null;entry.pending=null;entry.conflict=false;await saveShares();}
 if(!entry.pending){if(samePayload(entry.desired,entry.published))break;entry.pending={id:crypto.randomUUID(),revision:entry.revision||0,payload:entry.desired};await saveShares();}
 const operation=entry.pending;try{const revision=await api.publish(id,operation);entry.revision=revision;entry.published=operation.payload;entry.pending=null;entry.conflict=false;await saveShares();}catch(error){if(error.code==='40001'){const remote=(await api.publications(owner)).find(p=>p.game_id===id);if(entry.desired===null){entry.revision=remote?.revision||0;entry.published=remote?.operation_payload||null;entry.pending=null;entry.conflict=false;await saveShares();continue;}entry.conflict=true;await saveShares();}throw error;}}}}finally{publishing=false;emit();}}
function shareForm(id){const g=game(id);if(!g)return;const remote=ownPublications.find(p=>p.game_id===id),b=build('sharing',{});dialog={render:()=>b.page(T('Compartir progreso'),g.title,[text(T('Tus amigos verán título, plataforma, estado y progreso. Las notas y el texto de las tareas permanecen privados.')),text(remote?.operation_payload?T('Ya hay progreso publicado desde otro dispositivo o sesión. Al publicar usarás los datos que ves aquí.'):T('Solo se comparten los juegos que elijas.')),text(statusLabels()[g.status]+' · '+progress(g).text)],[b.button(T('Cancelar'),closeDialog,'cancel'),b.button(T('Publicar progreso'),async()=>{await attachShares();g.friendsPrivate=false;g.tracked=true;const entry=shares[id]||{};if(!publishing)Object.assign(entry,{revision:remote?.revision||0,published:remote?.operation_payload||null,pending:null,conflict:false});shares[id]=entry;await persist();planSharing();await saveShares();closeDialog();await flush();await loadFriends();},'publish'),b.button(T('Dejar de compartir'),async()=>{await attachShares();g.friendsPrivate=true;await persist();await saveShares();closeDialog();await flush();await loadFriends();},'withdraw')])};emit();}
async function signIn(create=false){if(authBusy)return;authBusy=true;emit();try{await api.login(friendFields.username||'',friendFields.password||'',create?(friendFields.name||friendFields.username||''):undefined);friendFields={};await loadFriends();await flush();}finally{authBusy=false;emit();}}
function friendsSchema(){const b=build('friend',friendFields);b.busy=friendsBusy||authBusy;const items=[];const button=(label,fn,id)=>b.button(label,fn,id);const profile=id=>profiles.find(p=>p.user_id===id);const name=id=>profile(id)?.display_name||T('Amigo');
 if(!api.social){const creating=authMode==='register';items.push(text(T(creating?'Crear cuenta':'Iniciar sesión'),true),text(T(creating?'Crea una cuenta de Checkpoint para compartir tu progreso.':'Accede con tu usuario y contraseña de Checkpoint.'),false,true),text(T('Tu biblioteca sigue disponible sin cuenta. La sesión dura en esta pestaña.'),false,true),...b.field('username',T('Usuario de Checkpoint')),...b.field('password',T('Contraseña de Checkpoint'),'password'));if(creating)items.push(...b.field('name',T('Nombre visible (para crear cuenta)')));items.push({type:'row',children:[button(T(creating?'Crear cuenta':'Entrar'),()=>signIn(creating),creating?'register':'login'),button(T(creating?'Ya tengo cuenta':'Crear cuenta'),()=>{authMode=creating?'login':'register';friendFields.password='';notice='';},'auth-mode')]});return {type:'stack',children:items};}
 items.push({type:'row',children:[['friends','Amigos'],['requests','Solicitudes'],['sharing','Compartir'],['account','Cuenta']].map(([id,label])=>button(T(label),async()=>{friendPage=id;selectedFriend=null;await loadFriends();},'tab.'+id))});
 if(friendPage==='account'){const own=profile(api.social.user.id);items.push(text(own?.display_name||T('Cuenta'),true),text(T('Código de amigo')),text(own?friendCode(own.friend_code):''),button(T('Copiar código'),async()=>{if(own)await navigator.clipboard.writeText(friendCode(own.friend_code));notice=T('Código copiado.');},'copy'),button(T('Cerrar sesión'),async()=>{await api.logout();shareUser=null;shares={};profiles=[];friendFields={};authMode='login';},'logout'));}
 else if(friendPage==='requests'){items.push(text(T('Solicitudes'),true));for(const r of requests){if(!uuid(r.id))continue;const incoming=r.recipient_id===api.social.user.id;items.push(text(name(incoming?r.sender_id:r.recipient_id)),{type:'row',children:incoming?[button(T('Aceptar'),async()=>{await api.answer(r.id,true);await loadFriends();},'accept.'+r.id),button(T('Rechazar'),async()=>{await api.answer(r.id,false);await loadFriends();},'reject.'+r.id)]:[button(T('Cancelar solicitud'),async()=>{await api.cancel(r.id);await loadFriends();},'cancel.'+r.id)]});}if(!requests.length)items.push(text(T('No hay solicitudes pendientes.')));}
 else if(friendPage==='sharing'){items.push(text(T('Compartir'),true),text(T('Los juegos de tus listas son visibles para tus amigos salvo que los marques privados. Notas y nombres de tareas siguen siendo privados.'),false,true));for(const g of data.games.filter(g=>g.tracked).slice(0,500))items.push({type:'card',children:[text(g.title),text(shares[g.id]?.conflict?T('Conflicto: revisa antes de publicar.'):shares[g.id]?.selected?T(samePayload(shares[g.id].desired,shares[g.id].published)?'Compartido':'Pendiente de publicar'):T(shares[g.id]?.published?'Retirada pendiente de conexión.':'Privado'),false,true),button(T('Gestionar publicación'),async()=>{await loadFriends();shareForm(g.id);},'share.'+g.id)]});}
 else if(selectedFriend){items.push(text(name(selectedFriend),true),button(T('Volver a amigos'),()=>{selectedFriend=null;},'back'));for(const p of publications){const g=p.operation_payload;if(!g||typeof g.title!=='string')continue;const state=Math.max(0,statuses.findIndex(s=>s.toLowerCase()===g.status));const details=[text(g.title),text((g.platform||'')+' · '+statusLabels()[state])];if(Number.isInteger(g.storyPercent))details.push(text(T('Historia')+': '+g.storyPercent+'%'));if(Number.isInteger(g.tasksTotal))details.push(text(`${T('Tareas')}: ${g.tasksDone}/${g.tasksTotal}`));if(Number.isInteger(g.achievementsTotal))details.push(text(`${T('Logros')}: ${g.achievementsUnlocked}/${g.achievementsTotal}`));if(!data.settings.lightweight&&Number.isInteger(g.steamAppId)&&g.steamAppId>0)details.unshift({type:'image',src:cover({steamAppId:g.steamAppId}),children:[]});items.push({type:'card',children:details});}if(!publications.length)items.push(text(T('Tu amigo aún no ha compartido juegos.')));}
 else{items.push(text(T('Tus amigos'),true),...b.field('code',T('Código de amigo (checkpoint-…)')),button(T('Enviar solicitud'),async()=>{await api.invite(friendFields.code||'');notice=T('Solicitud enviada.');await loadFriends();},'invite'));const own=api.social.user.id;for(const f of friendships){const id=f.user_low===own?f.user_high:f.user_low;if(!uuid(id))continue;items.push({type:'card',children:[text(name(id)),{type:'row',children:[button(T('Ver progreso'),async()=>{selectedFriend=id;await loadFriends();},'progress.'+id),button(T('Quitar amistad'),async()=>{await api.unfriend(id);await loadFriends();},'remove.'+id),button(T('Bloquear'),async()=>{await api.block(id);await loadFriends();},'block.'+id)]}]});}if(!friendships.length)items.push(text(T('Comparte tu código desde Cuenta. La amistad empieza cuando se acepta la solicitud.')));}
 items.push(button(T('Actualizar'),loadFriends,'refresh'));return {type:'stack',children:items};}
function download(){const exported={version:1,gameLists:data.settings.gameLists,exportedAt:new Date().toISOString(),games:data.games.map(g=>({...g,status:statuses[g.status],goal:goals[g.goal],customCover:null})),covers:Object.fromEntries(data.games.filter(g=>g.customCover?.startsWith('data:image/png;base64,')).map(g=>[g.id,g.customCover.split(',')[1]]))};const url=URL.createObjectURL(new Blob([JSON.stringify(exported,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='checkpoint-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function importer(){const fields={},b=build('import',fields);dialog={render:()=>{const items=b.field('file',T('Copia JSON de Checkpoint'),'file');items.at(-1).accept='.json,application/json';return b.page(T('Importar copia'),T('Se añadirán juegos nuevos. Los existentes y tus notas se conservan.'),items,[b.button(T('Cancelar'),closeDialog,'cancel'),b.button(T('Importar'),async()=>{if(!fields.file||fields.file.size>16777216)throw new Error('invalid-backup');const parsed=JSON.parse(await fields.file.text());const count=importBackup(data.games,parsed);data.settings.gameLists=normalizeLists([...(data.settings.gameLists||[]),...(parsed.gameLists||[])]);await persist();notice=`${count} ${T('juegos importados')}`;closeDialog();},'import')]);}};emit();}
async function command(message){ack=Math.max(ack,Number(message.requestId)||0);if(message.control){const handler=controls.get(String(message.control));if(handler)await handler(message.action==='value'?message.value:undefined);emit();return;}
 const g=game(message.id);switch(message.action){case'cover-missing':if(g)missingCover(g.id);break;case'ready':emit();if(api.steam)sync();if(api.social)loadFriends().then(flush).catch(fail);return;case'add':editor();return;case'achievements':if(g)achievements(g.id);return;case'details':if(g)gameDetails(g.id);return;case'edit':if(g)editor(g);return;case'configure-shortcuts':shortcutSettings();return;case'manage-lists':manageLists();return;case'privacy':if(g){g.friendsPrivate=message.value===true;await persist();await flush();}break;case'collection':if(message.value==='all'||message.value==='private'||data.settings.gameLists.some(n=>'custom:'+n===message.value)){data.settings.activeList=message.value;tab='list';search='';filter=0;await persist();}break;case'settings':settings();return;case'cancel-dialog':if(dialog?.cancel)await dialog.cancel();else closeDialog();return;case'account':if(!api.social){authMode='login';friendFields.password='';notice='';}tab='friends';friendPage=api.social?'account':'friends';selectedFriend=null;emit();if(api.social)await loadFriends();return;case'web-info':info();return;case'import':importer();return;case'export':download();return;case'steam':connectSteam();return;case'sync':if(api.steam)sync();else connectSteam();return;
 case'tab':if(['list','library','friends'].includes(message.value)){tab=message.value;if(tab==='friends')loadFriends();}break;case'search-change':search=String(message.value||'').slice(0,140);break;case'filter':filter=Math.max(0,Math.min(5,Number(message.value)||0));break;case'search':tab='list';emit();send({kind:'focus-search'});break;
 case'cycle':data.settings.layout=(data.settings.layout+1)%3;await persist();break;
 case'state':if(g&&Number.isInteger(message.value)&&message.value>=0&&message.value<5){g.status=message.value;g.finishedAt=g.status===3?(g.finishedAt||new Date().toISOString()):null;await persist();}break;case'finish':if(g){g.status=g.status===3?0:3;g.finishedAt=g.status===3?new Date().toISOString():null;await persist();}break;case'undo':{const restored=data.deleted.pop();if(restored&&!game(restored.id))data.games.push(normalize(restored));await persist();break;}
 case'move':{const target=game(message.target);if(g&&target&&g.id!==target.id&&g.favorite===target.favorite){const ordered=[...data.games].sort((a,b)=>Number(b.favorite)-Number(a.favorite)||a.sortOrder-b.sortOrder);ordered.splice(ordered.indexOf(g),1);ordered.splice(ordered.indexOf(target)+(message.after?1:0),0,g);ordered.forEach((x,i)=>x.sortOrder=i);await persist();}break;}
 case'examples':if(!data.games.length){data.games.push(normalize({title:'Hollow Knight',steamAppId:367520,platform:'Steam'}),normalize({title:'Hades',steamAppId:1145360,platform:'Steam',status:1,sortOrder:1}),normalize({title:'Portal 2',steamAppId:620,platform:'Steam',sortOrder:2}));await persist();}break;
 }emit();}
window.chrome=window.chrome||{};window.chrome.webview={addEventListener:(type,listener)=>{if(type==='message')listeners.push(listener);},postMessage:message=>command(message).catch(fail)};
let timer;function restartTimer(){clearInterval(timer);timer=setInterval(()=>{if(!document.hidden&&api.steam)sync();},Math.max(15,Math.min(120,data.settings.syncMinutes))*60000);}restartTimer();
setInterval(()=>{if(!document.hidden){flush().catch(fail);if(tab==='friends'&&!dialog)loadFriends();}},60000);
window.addEventListener('online',()=>{if(api.steam)sync();flush().catch(fail);});
await import('./ui.js');
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
